name: CI for Model Training and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengambil kode dari repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan environment Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Langkah 3: Menyiapkan Conda untuk environment MLProject
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12'

      # Langkah 4: Menginstall MLflow
      - name: Install MLflow
        run: pip install mlflow

      # Langkah 5: Menjalankan training model menggunakan MLProject
      # Ini akan menjalankan modelling.py dan menyimpan model ke folder 'output/model'
      - name: Run MLflow Project to train model
        shell: bash -l {0}
        run: mlflow run ./MLProject

      # Langkah 6: Login ke Docker Hub menggunakan secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Langkah 7: Membangun dan Mendorong (Push) Docker image
      - name: Build and Push Docker image explicitly
        # PENTING: Ganti 'username_anda' dengan username Docker Hub Anda
        env:
          IMAGE_NAME: hafelen09/churn-prediction-model
        run: |
          # 1. Bangun image secara lokal dari path yang sudah pasti
          mlflow models build-docker --model-uri "./MLProject/output/model" --name "$IMAGE_NAME"
          
          # 2. Push image tersebut secara eksplisit ke Docker Hub
          echo "Pushing image $IMAGE_NAME:latest to Docker Hub..."
          docker push "$IMAGE_NAME:latest"
          echo "Docker push command finished."

